FROM python:3.12-slim AS builder
WORKDIR /app

RUN apt-get update && apt-get install -y curl \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && ln -s /root/.local/bin/poetry /usr/local/bin/poetry

COPY . .
COPY README.md .

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --only main

FROM python:3.12-slim
WORKDIR /app

RUN apt-get update && apt-get install -y curl \
    && curl -sSL https://install.python-poetry.org | python3 - \
    && ln -s /root/.local/bin/poetry /usr/local/bin/poetry

COPY --from=builder /usr/local /usr/local
COPY --from=builder /app /app

ENV PYTHONPATH=/app:$PYTHONPATH

EXPOSE 8000

CMD ["/bin/bash", "-c", "\
    if [ \"$MODE\" != \"prod\" ]; then \
        poetry config virtualenvs.create false && \
        poetry install --no-interaction --no-ansi --directory $ML_HOMELAB_ROOT/ml-training; \
    fi && \
    python -u -m uvicorn src.ml_serving.investing_allocation_optimizer.serving:app \
        --host 0.0.0.0 --port 8000"]
